version: "3.9"

services:
  app:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/src/app
    command: ["npm", "start"]
